[package]
name = "liveOAR"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "liveOAR"
path = "src/main.rs"

[dependencies]
goard_core = { path = "../goard_core" }
eframe = "0.30.0"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
env_logger = "0.11"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3.70", features = ["Performance", "Document", "Window", "Element", "HtmlInputElement", "File", "FileList", "Blob", "FileReader"] }
js-sys = "0.3"
log = "0.4"
console_error_panic_hook = "0.1.7"
